version: '3.7'

services:
  nginx:
    # image: nginx
    build:
      context: ./requirements/nginx
    volumes:
      - wp_files:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - net_container

  wordpress:
    # image: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wp_files:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mariadb
    networks:
      - net_container

  mariadb:
    build:
      context: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - net_container
    hostname: mariadb

volumes:
  db_data:
  wp_files:

networks:
  net_container:
