FROM debian:bullseye-slim

# Nginxとopensslをインストール
RUN apt-get update && apt-get install -y nginx openssl

# SSL証明書及びキー設置用のディレクトリ作成
RUN mkdir -p /etc/nginx/ssl/

# 自己証明書の作成
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt \
    -subj "/CN=terabu.42.fr"

# 設定ファイル・スクリプトのコピー
COPY conf/default.conf /etc/nginx/sites-enabled/default
COPY tools/docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

EXPOSE 443

CMD ["/docker-entrypoint.sh"]
