FROM debian:bullseye-slim

# Install Nginx and openssl
RUN apt-get update && apt-get install -y nginx openssl curl iputils-ping vim

# Create a directory for the SSL certificate and key
RUN mkdir -p /etc/nginx/ssl/

# Generate a self-signed certificate
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt \
    -subj "/CN=terabu.42.fr"

# Copy custom configurations
COPY conf/default.conf /etc/nginx/sites-enabled/default
COPY tools/docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

EXPOSE 443

CMD ["/docker-entrypoint.sh"]
